# Generated by Django 2.1 on 2018-11-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityName',
            new_name='name',
        ),
    ]
